export const LICENSE_DISPLAY_NAMES: Record<string, string> = {
    "agpl-3.0": "GNU Affero General Public License v3.0",
    "apache-2.0": "Apache License 2.0",
    "bsd-2-clause": "BSD 2-Clause License",
    "bsd-3-clause": "BSD 3-Clause License",
    "bsl-1.0": "Boost Software License 1.0",
    "cc0-1.0": "Creative Commons Zero v1.0 Universal",
    "epl-2.0": "Eclipse Public License 2.0",
    "gpl-2.0": "GNU General Public License v2.0",
    "gpl-3.0": "GNU General Public License v3.0",
    "lgpl-2.1": "GNU Lesser General Public License v2.1",
    "mit": "MIT License",
    "mpl-2.0": "Mozilla Public License 2.0",
    "unlicense": "The Unlicense",
} as const;

export const GITIGNORE_TEMPLATES = [
    "AL",
    "Actionscript",
    "Ada",
    "AdventureGameStudio",
    "Agda",
    "Android",
    "Angular",
    "AppEngine",
    "AppceleratorTitanium",
    "ArchLinuxPackages",
    "Autotools",
    "Ballerina",
    "C",
    "C++",
    "CFWheels",
    "CMake",
    "CUDA",
    "CakePHP",
    "ChefCookbook",
    "Clojure",
    "CodeIgniter",
    "CommonLisp",
    "Composer",
    "Concrete5",
    "Coq",
    "CraftCMS",
    "D",
    "DM",
    "Dart",
    "Delphi",
    "Dotnet",
    "Drupal",
    "EPiServer",
    "Eagle",
    "Elisp",
    "Elixir",
    "Elm",
    "Erlang",
    "ExpressionEngine",
    "ExtJs",
    "Fancy",
    "Finale",
    "Firebase",
    "FlaxEngine",
    "Flutter",
    "ForceDotCom",
    "Fortran",
    "FuelPHP",
    "GWT",
    "Gcov",
    "GitBook",
    "GitHubPages",
    "Gleam",
    "Go",
    "Godot",
    "Gradle",
    "Grails",
    "HIP",
    "Haskell",
    "Haxe",
    "IAR",
    "IGORPro",
    "Idris",
    "JBoss",
    "JENKINS_HOME",
    "Java",
    "Jekyll",
    "Joomla",
    "Julia",
    "Katalon",
    "KiCad",
    "Kohana",
    "Kotlin",
    "LabVIEW",
    "LangChain",
    "Laravel",
    "Leiningen",
    "LemonStand",
    "Lilypond",
    "Lithium",
    "Lua",
    "Luau",
    "Magento",
    "Maven",
    "Mercury",
    "MetaProgrammingSystem",
    "Modelica",
    "Nanoc",
    "Nestjs",
    "Nextjs",
    "Nim",
    "Nix",
    "Node",
    "OCaml",
    "Objective-C",
    "Opa",
    "OpenCart",
    "OracleForms",
    "Packer",
    "Perl",
    "Phalcon",
    "PlayFramework",
    "Plone",
    "Prestashop",
    "Processing",
    "PureScript",
    "Python",
    "Qooxdoo",
    "Qt",
    "R",
    "ROS",
    "Racket",
    "Rails",
    "Raku",
    "ReScript",
    "RhodesRhomobile",
    "Ruby",
    "Rust",
    "SCons",
    "SSDT-sqlproj",
    "Sass",
    "Scala",
    "Scheme",
    "Scrivener",
    "Sdcc",
    "SeamGen",
    "SketchUp",
    "Smalltalk",
    "Solidity-Remix",
    "Stella",
    "SugarCRM",
    "Swift",
    "Symfony",
    "SymphonyCMS",
    "TeX",
    "Terraform",
    "TestComplete",
    "Textpattern",
    "TurboGears2",
    "TwinCAT3",
    "Typo3",
    "Unity",
    "UnrealEngine",
    "VBA",
    "VVVV",
    "VisualStudio",
    "Waf",
    "WordPress",
    "Xojo",
    "Yeoman",
    "Yii",
    "ZendFramework",
    "Zephir",
    "Zig",
    "ecu.test",
] as const;
