import { GI, L } from "./constants.js";

export const LICENSE_TEMPLATES = [
  {
    name: "agpl-3.0",
    label: "GNU Affero General Public License v3.0",
    value: L["agpl-3.0"],
  },
  {
    name: "apache-2.0",
    label: "Apache License 2.0",
    value: L["apache-2.0"],
  },
  {
    name: "bsd-2-clause",
    label: "BSD 2-Clause License",
    value: L["bsd-2-clause"],
  },
  {
    name: "bsd-3-clause",
    label: "BSD 3-Clause License",
    value: L["bsd-3-clause"],
  },
  {
    name: "bsl-1.0",
    label: "Boost Software License 1.0",
    value: L["bsl-1.0"],
  },
  {
    name: "cc0-1.0",
    label: "Creative Commons Zero v1.0 Universal",
    value: L["cc0-1.0"],
  },
  {
    name: "epl-2.0",
    label: "Eclipse Public License 2.0",
    value: L["epl-2.0"],
  },
  {
    name: "gpl-2.0",
    label: "GNU General Public License v2.0",
    value: L["gpl-2.0"],
  },
  {
    name: "gpl-3.0",
    label: "GNU General Public License v3.0",
    value: L["gpl-3.0"],
  },
  {
    name: "lgpl-2.1",
    label: "GNU Lesser General Public License v2.1",
    value: L["lgpl-2.1"],
  },
  { name: "mit", label: "MIT License", value: L["mit"] },
  {
    name: "mpl-2.0",
    label: "Mozilla Public License 2.0",
    value: L["mpl-2.0"],
  },
  { name: "unlicense", label: "The Unlicense", value: L["unlicense"] },
] as const;

export const GITIGNORE_TEMPLATES = [
  { name: "AL", value: GI["AL"] },
  { name: "Actionscript", value: GI["Actionscript"] },
  { name: "Ada", value: GI["Ada"] },
  { name: "AdventureGameStudio", value: GI["AdventureGameStudio"] },
  { name: "Agda", value: GI["Agda"] },
  { name: "Android", value: GI["Android"] },
  { name: "Angular", value: GI["Angular"] },
  { name: "AppEngine", value: GI["AppEngine"] },
  { name: "AppceleratorTitanium", value: GI["AppceleratorTitanium"] },
  { name: "ArchLinuxPackages", value: GI["ArchLinuxPackages"] },
  { name: "Autotools", value: GI["Autotools"] },
  { name: "Ballerina", value: GI["Ballerina"] },
  { name: "C", value: GI["C"] },
  { name: "C++", value: GI["C++"] },
  { name: "CFWheels", value: GI["CFWheels"] },
  { name: "CMake", value: GI["CMake"] },
  { name: "CUDA", value: GI["CUDA"] },
  { name: "CakePHP", value: GI["CakePHP"] },
  { name: "ChefCookbook", value: GI["ChefCookbook"] },
  { name: "Clojure", value: GI["Clojure"] },
  { name: "CodeIgniter", value: GI["CodeIgniter"] },
  { name: "CommonLisp", value: GI["CommonLisp"] },
  { name: "Composer", value: GI["Composer"] },
  { name: "Concrete5", value: GI["Concrete5"] },
  { name: "Coq", value: GI["Coq"] },
  { name: "CraftCMS", value: GI["CraftCMS"] },
  { name: "D", value: GI["D"] },
  { name: "DM", value: GI["DM"] },
  { name: "Dart", value: GI["Dart"] },
  { name: "Delphi", value: GI["Delphi"] },
  { name: "Dotnet", value: GI["Dotnet"] },
  { name: "Drupal", value: GI["Drupal"] },
  { name: "EPiServer", value: GI["EPiServer"] },
  { name: "Eagle", value: GI["Eagle"] },
  { name: "Elisp", value: GI["Elisp"] },
  { name: "Elixir", value: GI["Elixir"] },
  { name: "Elm", value: GI["Elm"] },
  { name: "Erlang", value: GI["Erlang"] },
  { name: "ExpressionEngine", value: GI["ExpressionEngine"] },
  { name: "ExtJs", value: GI["ExtJs"] },
  { name: "Fancy", value: GI["Fancy"] },
  { name: "Finale", value: GI["Finale"] },
  { name: "Firebase", value: GI["Firebase"] },
  { name: "FlaxEngine", value: GI["FlaxEngine"] },
  { name: "Flutter", value: GI["Flutter"] },
  { name: "ForceDotCom", value: GI["ForceDotCom"] },
  { name: "Fortran", value: GI["Fortran"] },
  { name: "FuelPHP", value: GI["FuelPHP"] },
  { name: "GWT", value: GI["GWT"] },
  { name: "Gcov", value: GI["Gcov"] },
  { name: "GitBook", value: GI["GitBook"] },
  { name: "GitHubPages", value: GI["GitHubPages"] },
  { name: "Gleam", value: GI["Gleam"] },
  { name: "Go", value: GI["Go"] },
  { name: "Godot", value: GI["Godot"] },
  { name: "Gradle", value: GI["Gradle"] },
  { name: "Grails", value: GI["Grails"] },
  { name: "HIP", value: GI["HIP"] },
  { name: "Haskell", value: GI["Haskell"] },
  { name: "Haxe", value: GI["Haxe"] },
  { name: "IAR", value: GI["IAR"] },
  { name: "IGORPro", value: GI["IGORPro"] },
  { name: "Idris", value: GI["Idris"] },
  { name: "JBoss", value: GI["JBoss"] },
  { name: "JENKINS_HOME", value: GI["JENKINS_HOME"] },
  { name: "Java", value: GI["Java"] },
  { name: "Jekyll", value: GI["Jekyll"] },
  { name: "Joomla", value: GI["Joomla"] },
  { name: "Julia", value: GI["Julia"] },
  { name: "Katalon", value: GI["Katalon"] },
  { name: "KiCad", value: GI["KiCad"] },
  { name: "Kohana", value: GI["Kohana"] },
  { name: "Kotlin", value: GI["Kotlin"] },
  { name: "LabVIEW", value: GI["LabVIEW"] },
  { name: "LangChain", value: GI["LangChain"] },
  { name: "Laravel", value: GI["Laravel"] },
  { name: "Leiningen", value: GI["Leiningen"] },
  { name: "LemonStand", value: GI["LemonStand"] },
  { name: "Lilypond", value: GI["Lilypond"] },
  { name: "Lithium", value: GI["Lithium"] },
  { name: "Lua", value: GI["Lua"] },
  { name: "Luau", value: GI["Luau"] },
  { name: "Magento", value: GI["Magento"] },
  { name: "Maven", value: GI["Maven"] },
  { name: "Mercury", value: GI["Mercury"] },
  { name: "MetaProgrammingSystem", value: GI["MetaProgrammingSystem"] },
  { name: "Modelica", value: GI["Modelica"] },
  { name: "Nanoc", value: GI["Nanoc"] },
  { name: "Nestjs", value: GI["Nestjs"] },
  { name: "Nextjs", value: GI["Nextjs"] },
  { name: "Nim", value: GI["Nim"] },
  { name: "Nix", value: GI["Nix"] },
  { name: "Node", value: GI["Node"] },
  { name: "OCaml", value: GI["OCaml"] },
  { name: "Objective-C", value: GI["Objective-C"] },
  { name: "Opa", value: GI["Opa"] },
  { name: "OpenCart", value: GI["OpenCart"] },
  { name: "OracleForms", value: GI["OracleForms"] },
  { name: "Packer", value: GI["Packer"] },
  { name: "Perl", value: GI["Perl"] },
  { name: "Phalcon", value: GI["Phalcon"] },
  { name: "PlayFramework", value: GI["PlayFramework"] },
  { name: "Plone", value: GI["Plone"] },
  { name: "Prestashop", value: GI["Prestashop"] },
  { name: "Processing", value: GI["Processing"] },
  { name: "PureScript", value: GI["PureScript"] },
  { name: "Python", value: GI["Python"] },
  { name: "Qooxdoo", value: GI["Qooxdoo"] },
  { name: "Qt", value: GI["Qt"] },
  { name: "R", value: GI["R"] },
  { name: "ROS", value: GI["ROS"] },
  { name: "Racket", value: GI["Racket"] },
  { name: "Rails", value: GI["Rails"] },
  { name: "Raku", value: GI["Raku"] },
  { name: "ReScript", value: GI["ReScript"] },
  { name: "RhodesRhomobile", value: GI["RhodesRhomobile"] },
  { name: "Ruby", value: GI["Ruby"] },
  { name: "Rust", value: GI["Rust"] },
  { name: "SCons", value: GI["SCons"] },
  { name: "SSDT-sqlproj", value: GI["SSDT-sqlproj"] },
  { name: "Sass", value: GI["Sass"] },
  { name: "Scala", value: GI["Scala"] },
  { name: "Scheme", value: GI["Scheme"] },
  { name: "Scrivener", value: GI["Scrivener"] },
  { name: "Sdcc", value: GI["Sdcc"] },
  { name: "SeamGen", value: GI["SeamGen"] },
  { name: "SketchUp", value: GI["SketchUp"] },
  { name: "Smalltalk", value: GI["Smalltalk"] },
  { name: "Solidity-Remix", value: GI["Solidity-Remix"] },
  { name: "Stella", value: GI["Stella"] },
  { name: "SugarCRM", value: GI["SugarCRM"] },
  { name: "Swift", value: GI["Swift"] },
  { name: "Symfony", value: GI["Symfony"] },
  { name: "SymphonyCMS", value: GI["SymphonyCMS"] },
  { name: "TeX", value: GI["TeX"] },
  { name: "Terraform", value: GI["Terraform"] },
  { name: "TestComplete", value: GI["TestComplete"] },
  { name: "Textpattern", value: GI["Textpattern"] },
  { name: "TurboGears2", value: GI["TurboGears2"] },
  { name: "TwinCAT3", value: GI["TwinCAT3"] },
  { name: "Typo3", value: GI["Typo3"] },
  { name: "Unity", value: GI["Unity"] },
  { name: "UnrealEngine", value: GI["UnrealEngine"] },
  { name: "VBA", value: GI["VBA"] },
  { name: "VVVV", value: GI["VVVV"] },
  { name: "VisualStudio", value: GI["VisualStudio"] },
  { name: "Waf", value: GI["Waf"] },
  { name: "WordPress", value: GI["WordPress"] },
  { name: "Xojo", value: GI["Xojo"] },
  { name: "Yeoman", value: GI["Yeoman"] },
  { name: "Yii", value: GI["Yii"] },
  { name: "ZendFramework", value: GI["ZendFramework"] },
  { name: "Zephir", value: GI["Zephir"] },
  { name: "Zig", value: GI["Zig"] },
  { name: "ecu.test", value: GI["ecu.test"] },
];
